// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPivBMK9JnpoFnF6PTQtZ9XnyDsE6wQys',
    appId: '1:92733736833:android:548065ba2b7178f726ca80',
    messagingSenderId: '92733736833',
    projectId: 'webrtc-flutter-1c8be',
    storageBucket: 'webrtc-flutter-1c8be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOPnCJXQhVNnGYH6SMdS7fQkpRUZBPtz0',
    appId: '1:285850802871:ios:d48099e0426573a0ca8b32',
    messagingSenderId: '285850802871',
    projectId: 'xenett-82b18',
    storageBucket: 'xenett-82b18.firebasestorage.app',
    iosClientId:'1:285850802871:android:3403fbfd18cde7ddca8b32',
    iosBundleId: 'com.xenett.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOPnCJXQhVNnGYH6SMdS7fQkpRUZBPtz0',
    appId: '1:285850802871:ios:d48099e0426573a0ca8b32',
    messagingSenderId: '285850802871',
    projectId: 'xenett-82b18',
    storageBucket: 'xenett-82b18.firebasestorage.app',
    iosBundleId: 'com.xenett.app',
  );
}
